- name: Demo On Play level Variables
  hosts: all
  vars:
    URL: play.exmaple.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
         msg: URL - {{ URL }}
  # In ansible variable will be accessed using {{ }}
  #Ansible support double quotes kk single quote also,how ever quotes are not mandatory in all cases,
  #quotes are mandatory if value starts with a variable , meaning
  #msg: {{ URL }} < - This requires quoting
  #msg: URL - {{ URL }} < - This doesnot requires quoting

 - name: Demo On Task level Variables
   hosts: all
  tasks:
        - name: Print URL
          ansible.builtin.debug:
            msg: URL - {{ URL }}
   vars:
        URL: play.exmaple.com
  #only that task have that variable,other tasks cannot access it