- name: Demo On Play level Variables
  hosts: all
  vars:
    URL: play.exmaple.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
         msg: URL - {{ URL }}
  # In ansible variable will be accessed using {{ }}
  #Ansible support double quotes kk single quote also,how ever quotes are not mandatory in all cases,
  #quotes are mandatory if value starts with a variable , meaning
  #msg: {{ URL }} < - This requires quoting
  #msg: URL - {{ URL }} < - This doesnot requires quoting

- name: Load vars from a file
  hosts: all
  vars_files:
    - exvars.yaml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
       msg: URL - {{ URL }}
#var_files does not support task level, it is for play level only

- name: Demo On Task level Variables
  hosts: all
  tasks:
      - name: Print URL
        ansible.builtin.debug:
          msg: URL - {{ URL }}
        vars:
          URL: task .exmaple.com
  #only that task have that variable,other tasks cannot access it

- name: variable from roles
  hosts: all
  vars:
    URL_PLAY: play.example.com
  roles:
    - sample

- name: Demo on register variables
  hosts: all
  tasks:
    - name: Run uptime shell command
      ansible.builtin.shell: uptime
      register: output
    - name: print output
      ansible.builtin.debug:
        msg: '{{ output }}'